spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/a1_ecommerce_db
    username: postgres
    password: lily123
    driver-class-name: org.postgresql.Driver
  application:
    name: a01-a1-webmvc

server:
  port: 1919

